image: codelovers/nodejs-aws-cli

pipelines:
  live:
      - step:
          script:
            - apt-get update
            - apt-get install zip -y
            - aws configure set aws_access_key_id $ACCESS_KEY 
            - aws configure set aws_secret_access_key $SECERT_KEY
            - aws configure set region $REGION
            - aws configure set default_output_format json
            - cd deploy
            - mkdir -p src
            - cd src
            - mkdir -p lib
            - cd ..
            - bash deploy.sh
            - bash push.sh